//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainEx.Resources.Strings {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainEx.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture)!;
        public static string StatusIdle => ResourceManager.GetString("StatusIdle", resourceCulture)!;
        public static string StatusListening => ResourceManager.GetString("StatusListening", resourceCulture)!;
        public static string StatusStopped => ResourceManager.GetString("StatusStopped", resourceCulture)!;
        public static string StatusNoPermission => ResourceManager.GetString("StatusNoPermission", resourceCulture)!;
        public static string StatusError => ResourceManager.GetString("StatusError", resourceCulture)!;
        public static string BtnListen => ResourceManager.GetString("BtnListen", resourceCulture)!;
        public static string BtnStop => ResourceManager.GetString("BtnStop", resourceCulture)!;
        public static string BtnStart => ResourceManager.GetString("BtnStart", resourceCulture)!;
        public static string BtnDone => ResourceManager.GetString("BtnDone", resourceCulture)!;
        public static string BtnIDE => ResourceManager.GetString("BtnIDE", resourceCulture)!;
        public static string BtnClearDone => ResourceManager.GetString("BtnClearDone", resourceCulture)!;
        public static string BtnShowDone => ResourceManager.GetString("BtnShowDone", resourceCulture)!;
        public static string BtnHideDone => ResourceManager.GetString("BtnHideDone", resourceCulture)!;
        public static string StatPending => ResourceManager.GetString("StatPending", resourceCulture)!;
        public static string StatInProgress => ResourceManager.GetString("StatInProgress", resourceCulture)!;
        public static string EmptyTitle => ResourceManager.GetString("EmptyTitle", resourceCulture)!;
        public static string EmptySubtitle => ResourceManager.GetString("EmptySubtitle", resourceCulture)!;
        public static string ManualPlaceholder => ResourceManager.GetString("ManualPlaceholder", resourceCulture)!;
        public static string SwipeDone => ResourceManager.GetString("SwipeDone", resourceCulture)!;
        public static string SourceManual => ResourceManager.GetString("SourceManual", resourceCulture)!;
    }
}
